env:
    DEVICE_CODENAME: topaz # Enter your device codename
    ROMREPO: https://github.com/ArrowOS-Extended/android_manifest.git -b arrow-13.1 # Enter ROM repo link
    LOCALMANIFEST: https://github.com/belowzeroiq/local_manifest.git -b arrow-64 # Enter local_manifest link
    MAKEFILENAME: arrow_topaz # Enter makefile name (example: aosp_fleur)
    VARIANT: userdebug # Enter build variant (eng, user, userdebug)
    EXTRACMD: mv vendor/qcom/opensource/commonsys/display/services/config/src/Android.bp vendor/qcom/opensource/commonsys/display/services/config/src/Android.bp.bak # If you want to run any extra command before build
    TARGET: m bacon # Enter target (example: m bacon, make bacon, mka bacon)
    PIXELDRAIN_API_KEY: "ENCRYPTED[e5efcf15cfc42f5f5728245b2db391e0d87f0da6fa2f44862dfb9b2b63bb1785cdad933cf040a6a11fa6d68fb85524c3]"

# DONT MODIFY FROM HERE #
task:
  name: "AOSP"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G

  Setup_script:
      - ./scripts/setup.sh || source scripts/setup.sh

  Sync_script:
      - ./scripts/sync.sh || source scripts/sync.sh

  Requirements_script:
      - ./scripts/device_requirements.sh || source scripts/device_requirements.sh

  Build_script:
      - ./scripts/build.sh || source scripts/build.sh

  Upload_script:
      - ./scripts/upload.sh || source scripts/upload.sh
