env:
    DEVICE: topaz # Enter your device codename
    ROMREPO: https://github.com/LineageOS/android.git -b lineage-20.0 # Enter ROM repo link
    LOCALMANIFEST: https://github.com/belowzeroiq/local_manifest.git # Enter local_manifest link
    MAKEFILENAME: lineage_topaz # Enter makefile name (example: aosp_fleur)
    VARIENT: userdebug # Enter build variant (eng, user, userdebug)
    EXTRACMD: # If you want to run any extra command before build
    TARGET: mka bacon # Enter target (example: m bacon, make bacon, mka bacon)

# DONT MODIFY FROM HERE #
task:
  name: "AOSP"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G

  Setup_script:
      - |
        echo "Enabling ZRAM (50GB)..."
        sudo modprobe zram
        echo lz4 | sudo tee /sys/block/zram0/comp_algorithm
        echo $((50*1024*1024*1024)) | sudo tee /sys/block/zram0/disksize
        sudo mkswap /dev/zram0
        sudo swapon /dev/zram0 -p 100
        free -h  # Check memory status
      - ./scripts/setup.sh || source scripts/setup.sh

  Sync_script:
      - ./scripts/sync.sh || source scripts/sync.sh

  Build_script:
      - ./scripts/build.sh || source scripts/build.sh

  Upload_script:
      - ./scripts/upload.sh || source scripts/upload.sh
