env:
    DEVICE: topaz # Enter your device codename
    ROMREPO: https://github.com/LineageOS/android.git -b lineage-20.0 # Enter ROM repo link
    LOCALMANIFEST: https://github.com/belowzeroiq/local_manifest.git # Enter local_manifest link
    MAKEFILENAME: lineage_topaz # Enter makefile name (example: aosp_fleur)
    VARIENT: userdebug # Enter build variant (eng, user, userdebug)
    EXTRACMD: rm -rf hardware/qcom-caf/sm6225/display/services/config/src/Android.bp && rm -rf hardware/qcom-caf/sm6225/display/gralloc/Android.bp && rm -rf hardware/qcom-caf/sm6225/display/libqdmetadata/Android.bp # If you want to run any extra command before build
    TARGET: mka bacon # Enter target (example: m bacon, make bacon, mka bacon)

# DONT MODIFY FROM HERE #
task:
  name: "AOSP"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G

  Setup_script:
      - ./scripts/setup.sh || source scripts/setup.sh

  Sync_script:
      - ./scripts/sync.sh || source scripts/sync.sh

  Build_script:
      - ./scripts/build.sh || source scripts/build.sh

  Upload_script:
      - ./scripts/upload.sh || source scripts/upload.sh
