env:
    DEVICE: topaz # Enter your device codename
    ROMREPO: https://github.com/LineageOS/android.git -b lineage-20.0 # Enter ROM repo link
    LOCALMANIFEST: https://github.com/belowzeroiq/local_manifest.git # Enter local_manifest link
    MAKEFILENAME: lineage_topaz # Enter makefile name (example: aosp_fleur)
    VARIENT: userdebug # Enter build variant (eng, user, userdebug)
    EXTRACMD: # If you want to run any extra command before build
    TARGET: mka bacon # Enter target (example: m bacon, make bacon, mka bacon)

# DONT MODIFY FROM HERE #
task:
  name: "AOSP"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G

  Setup_script:
      - |
        echo "Setting up swap (50GB)..."
        sudo fallocate -l 50G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        free -h  # Verify swap is active
      - ./scripts/setup.sh || source scripts/setup.sh

  Sync_script:
      - ./scripts/sync.sh || source scripts/sync.sh

  Build_script:
      - ./scripts/build.sh || source scripts/build.sh

  Upload_script:
      - ./scripts/upload.sh || source scripts/upload.sh
